// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwg6Xnqb1S8YyFnf5SX4kSHovBbZXjKsY',
    appId: '1:929079196105:android:6afb49225825334d135018',
    messagingSenderId: '929079196105',
    projectId: 'educastock-20a98',
    storageBucket: 'educastock-20a98.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpGKVI4MLY4HoevJ5cMTb2LmUU08gHW2U',
    appId: '1:929079196105:ios:047cc7c1ac675980135018',
    messagingSenderId: '929079196105',
    projectId: 'educastock-20a98',
    storageBucket: 'educastock-20a98.firebasestorage.app',
    iosBundleId: 'br.org.casadacrianca.educastock',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq3ZvD6Wqqz0r3BMVzmB789m9pkfubNk8',
    appId: '1:929079196105:web:621eed3d4e4701e3135018',
    messagingSenderId: '929079196105',
    projectId: 'educastock-20a98',
    authDomain: 'educastock-20a98.firebaseapp.com',
    storageBucket: 'educastock-20a98.firebasestorage.app',
    measurementId: 'G-9DD0Z6TVMC',
  );

}